# Generated by Django 5.0.6 on 2024-06-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
