# Generated by Django 5.0.6 on 2024-06-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection(title)
        VALUES('Soap')
        """, """
        DELETE FROM store_collection
        WHERE title='Soap'
        """)
    ]
