# Generated by Django 5.0.6 on 2024-06-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='promotion',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.customer'),
        ),
    ]
